### ISSUE TITLE
create a conda environment with the latest version of sourmash

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/sourmash-examples#6]
Per @bluegenes tested by @jessicalumian. 

Create a file `sourmash-latest.yml` containing the dependencies, plus a pointer to the latest version of sourmash:
```yaml
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - rust
  - pip
  - pip:
    - git+https://github.com/sourmash-bio/sourmash@latest
```
and then run:
```shell
conda env create -f sourmash-latest.yaml
```
